//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Common.proto
namespace Common
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"struct_game_info")]
  public partial class struct_game_info : global::ProtoBuf.IExtensible
  {
    public struct_game_info() {}
    
    private uint _game_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"game_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint game_type
    {
      get { return _game_type; }
      set { _game_type = value; }
    }
    private string _game_ip;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"game_ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string game_ip
    {
      get { return _game_ip; }
      set { _game_ip = value; }
    }
    private uint _game_port;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"game_port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint game_port
    {
      get { return _game_port; }
      set { _game_port = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"struct_user_info")]
  public partial class struct_user_info : global::ProtoBuf.IExtensible
  {
    public struct_user_info() {}
    
    private uint _user_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private string _user_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"user_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string user_name
    {
      get { return _user_name; }
      set { _user_name = value; }
    }
    private uint _money;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint money
    {
      get { return _money; }
      set { _money = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"struct_room_info")]
  public partial class struct_room_info : global::ProtoBuf.IExtensible
  {
    public struct_room_info() {}
    
    private uint _room_index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint room_index
    {
      get { return _room_index; }
      set { _room_index = value; }
    }
    private uint _room_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"room_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint room_type
    {
      get { return _room_type; }
      set { _room_type = value; }
    }
    private uint _min_money;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"min_money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint min_money
    {
      get { return _min_money; }
      set { _min_money = value; }
    }
    private uint _max_money;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"max_money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint max_money
    {
      get { return _max_money; }
      set { _max_money = value; }
    }
    private uint _table_count;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"table_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint table_count
    {
      get { return _table_count; }
      set { _table_count = value; }
    }
    private uint _seat_num;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"seat_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint seat_num
    {
      get { return _seat_num; }
      set { _seat_num = value; }
    }
    private string _description;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string description
    {
      get { return _description; }
      set { _description = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"struct_table_user_info")]
  public partial class struct_table_user_info : global::ProtoBuf.IExtensible
  {
    public struct_table_user_info() {}
    
    private uint _user_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private string _user_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"user_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string user_name
    {
      get { return _user_name; }
      set { _user_name = value; }
    }
    private uint _seat_index;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"seat_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint seat_index
    {
      get { return _seat_index; }
      set { _seat_index = value; }
    }

    private uint _money = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint money
    {
      get { return _money; }
      set { _money = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"struct_table_info")]
  public partial class struct_table_info : global::ProtoBuf.IExtensible
  {
    public struct_table_info() {}
    
    private uint _table_index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"table_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint table_index
    {
      get { return _table_index; }
      set { _table_index = value; }
    }
    private uint _table_state;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"table_state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint table_state
    {
      get { return _table_state; }
      set { _table_state = value; }
    }
    private uint _table_seat_count;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"table_seat_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint table_seat_count
    {
      get { return _table_seat_count; }
      set { _table_seat_count = value; }
    }
    private readonly global::System.Collections.Generic.List<struct_table_user_info> _table_user_list = new global::System.Collections.Generic.List<struct_table_user_info>();
    [global::ProtoBuf.ProtoMember(4, Name=@"table_user_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<struct_table_user_info> table_user_list
    {
      get { return _table_user_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}